package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anasyalaili
 */
public class GUIPesanTiket extends javax.swing.JFrame {

    /**
     * Creates new form GUIPesanTiket
     */
    public GUIPesanTiket() {
        initComponents();
        pnlFilm1.setVisible(false);
        pnlFilm2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHome = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnFilm2 = new javax.swing.JButton();
        btnFilm4 = new javax.swing.JButton();
        btnFilm1 = new javax.swing.JButton();
        btnFilm3 = new javax.swing.JButton();
        lblWhatsNow = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlFilm1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblDurasi = new javax.swing.JLabel();
        posterFilm1 = new javax.swing.JButton();
        btnBook1 = new javax.swing.JButton();
        pnlTop2 = new javax.swing.JPanel();
        lblHeading2 = new javax.swing.JLabel();
        pnlBottom2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        areaSinopsis = new javax.swing.JScrollPane();
        txtSinopsis = new javax.swing.JTextArea();
        pnlFilm2 = new javax.swing.JPanel();
        lblJudul2 = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        lblDurasi2 = new javax.swing.JLabel();
        posterFilm2 = new javax.swing.JButton();
        btnBook2 = new javax.swing.JButton();
        pnlTop3 = new javax.swing.JPanel();
        lblHeading3 = new javax.swing.JLabel();
        pnlBottom3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        areaSinopsis2 = new javax.swing.JScrollPane();
        txtSinopsis2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setSize(new java.awt.Dimension(900, 600));

        pnlMainHome.setBackground(new java.awt.Color(69, 69, 69));
        pnlMainHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMainHome.setSize(new java.awt.Dimension(900, 600));

        pnlTop.setBackground(new java.awt.Color(74, 99, 124));

        lblHeading.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setText("CINEMAXX");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addGap(30, 30, 30))
        );

        btnFilm2.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_TTB.jpg")); // NOI18N
        btnFilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm2ActionPerformed(evt);
            }
        });

        btnFilm4.setText("Film4");

        btnFilm1.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_endgame.jpg")); // NOI18N
        btnFilm1.setIconTextGap(0);
        btnFilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm1ActionPerformed(evt);
            }
        });

        btnFilm3.setText("Film3");

        lblWhatsNow.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblWhatsNow.setForeground(new java.awt.Color(255, 255, 255));
        lblWhatsNow.setText("Now Showing");

        pnlBottom.setBackground(new java.awt.Color(74, 99, 124));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOUT CINEMAXX");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FAQ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTACT US");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MEMBERSHIP");

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainHomeLayout = new javax.swing.GroupLayout(pnlMainHome);
        pnlMainHome.setLayout(pnlMainHomeLayout);
        pnlMainHomeLayout.setHorizontalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainHomeLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWhatsNow)
                    .addGroup(pnlMainHomeLayout.createSequentialGroup()
                        .addComponent(btnFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainHomeLayout.setVerticalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblWhatsNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainHomeLayout.createSequentialGroup()
                        .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainHomeLayout.createSequentialGroup()
                        .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pnlFilm1.setBackground(new java.awt.Color(69, 69, 69));
        pnlFilm1.setToolTipText("");
        pnlFilm1.setSize(new java.awt.Dimension(900, 600));

        lblJudul.setFont(new java.awt.Font("Helvetica Neue", 1, 27)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Avengers: Endgame");

        btnBack.setBackground(new java.awt.Color(60, 80, 100));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDurasi.setForeground(new java.awt.Color(255, 255, 255));
        lblDurasi.setText("3h 1m");

        posterFilm1.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/1poster_endgame.jpg")); // NOI18N
        posterFilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posterFilm1ActionPerformed(evt);
            }
        });

        btnBook1.setBackground(new java.awt.Color(60, 80, 100));
        btnBook1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnBook1.setForeground(new java.awt.Color(255, 255, 255));
        btnBook1.setText("Book Now >>");

        pnlTop2.setBackground(new java.awt.Color(74, 99, 124));

        lblHeading2.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblHeading2.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading2.setText("CINEMAXX");

        javax.swing.GroupLayout pnlTop2Layout = new javax.swing.GroupLayout(pnlTop2);
        pnlTop2.setLayout(pnlTop2Layout);
        pnlTop2Layout.setHorizontalGroup(
            pnlTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTop2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTop2Layout.setVerticalGroup(
            pnlTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTop2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblHeading2)
                .addGap(30, 30, 30))
        );

        pnlBottom2.setBackground(new java.awt.Color(74, 99, 124));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ABOUT CINEMAXX");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FAQ");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONTACT US");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MEMBERSHIP");

        javax.swing.GroupLayout pnlBottom2Layout = new javax.swing.GroupLayout(pnlBottom2);
        pnlBottom2.setLayout(pnlBottom2Layout);
        pnlBottom2Layout.setHorizontalGroup(
            pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottom2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33))
        );
        pnlBottom2Layout.setVerticalGroup(
            pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottom2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtSinopsis.setBackground(new java.awt.Color(69, 69, 69));
        txtSinopsis.setColumns(20);
        txtSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        txtSinopsis.setLineWrap(true);
        txtSinopsis.setRows(5);
        txtSinopsis.setText("After Thanos' tragic defeat that wiped out half the universe, the remaining Avengers unite to travel back in time, collect the Infinity Stones, and reverse the destruction. In an epic final battle, they face Thanos once again to save the world—sacrificing many, including Iron Man, who dies in the name of humanity's victory.");
        areaSinopsis.setViewportView(txtSinopsis);

        javax.swing.GroupLayout pnlFilm1Layout = new javax.swing.GroupLayout(pnlFilm1);
        pnlFilm1.setLayout(pnlFilm1Layout);
        pnlFilm1Layout.setHorizontalGroup(
            pnlFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFilm1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posterFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnlFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul)
                    .addComponent(lblDurasi)
                    .addComponent(btnBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFilm1Layout.setVerticalGroup(
            pnlFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilm1Layout.createSequentialGroup()
                .addComponent(pnlTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlFilm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilm1Layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDurasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posterFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(pnlBottom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlFilm2.setBackground(new java.awt.Color(69, 69, 69));
        pnlFilm2.setToolTipText("");
        pnlFilm2.setSize(new java.awt.Dimension(900, 600));

        lblJudul2.setFont(new java.awt.Font("Helvetica Neue", 1, 27)); // NOI18N
        lblJudul2.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul2.setText("Train To Busan");

        btnBack2.setBackground(new java.awt.Color(60, 80, 100));
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        lblDurasi2.setForeground(new java.awt.Color(255, 255, 255));
        lblDurasi2.setText("1h 58m");

        posterFilm2.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/1post_TTB.jpg")); // NOI18N
        posterFilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posterFilm2ActionPerformed(evt);
            }
        });

        btnBook2.setBackground(new java.awt.Color(60, 80, 100));
        btnBook2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnBook2.setForeground(new java.awt.Color(255, 255, 255));
        btnBook2.setText("Book Now >>");

        pnlTop3.setBackground(new java.awt.Color(74, 99, 124));

        lblHeading3.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblHeading3.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading3.setText("CINEMAXX");

        javax.swing.GroupLayout pnlTop3Layout = new javax.swing.GroupLayout(pnlTop3);
        pnlTop3.setLayout(pnlTop3Layout);
        pnlTop3Layout.setHorizontalGroup(
            pnlTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTop3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTop3Layout.setVerticalGroup(
            pnlTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTop3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblHeading3)
                .addGap(30, 30, 30))
        );

        pnlBottom3.setBackground(new java.awt.Color(74, 99, 124));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ABOUT CINEMAXX");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("FAQ");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONTACT US");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("MEMBERSHIP");

        javax.swing.GroupLayout pnlBottom3Layout = new javax.swing.GroupLayout(pnlBottom3);
        pnlBottom3.setLayout(pnlBottom3Layout);
        pnlBottom3Layout.setHorizontalGroup(
            pnlBottom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottom3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addGroup(pnlBottom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(33, 33, 33))
        );
        pnlBottom3Layout.setVerticalGroup(
            pnlBottom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottom3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtSinopsis2.setBackground(new java.awt.Color(69, 69, 69));
        txtSinopsis2.setColumns(20);
        txtSinopsis2.setForeground(new java.awt.Color(255, 255, 255));
        txtSinopsis2.setLineWrap(true);
        txtSinopsis2.setRows(5);
        txtSinopsis2.setText("Sok-woo, a father with not much time for his daughter, Soo-ahn, are boarding the KTX- a fast train that shall bring them from Seoul to Busan. But during their journey, the apocalypse begins, and most of the earth's population become flesh craving zombies. While the KTX is shooting towards Busan, the passenger's fight for their families and lives against the zombies - and each other.");
        areaSinopsis2.setViewportView(txtSinopsis2);

        javax.swing.GroupLayout pnlFilm2Layout = new javax.swing.GroupLayout(pnlFilm2);
        pnlFilm2.setLayout(pnlFilm2Layout);
        pnlFilm2Layout.setHorizontalGroup(
            pnlFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFilm2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posterFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnlFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJudul2)
                    .addComponent(lblDurasi2)
                    .addComponent(btnBook2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaSinopsis2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFilm2Layout.setVerticalGroup(
            pnlFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilm2Layout.createSequentialGroup()
                .addComponent(pnlTop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlFilm2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFilm2Layout.createSequentialGroup()
                        .addComponent(lblJudul2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDurasi2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaSinopsis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBook2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posterFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(pnlBottom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFilm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFilm2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFilm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFilm2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm1ActionPerformed
        pnlMainHome.setVisible(false);
        pnlFilm1.setVisible(true);
    }//GEN-LAST:event_btnFilm1ActionPerformed

    private void btnFilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm2ActionPerformed
        pnlMainHome.setVisible(false);
        pnlFilm2.setVisible(true);
    }//GEN-LAST:event_btnFilm2ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        pnlFilm1.setVisible(false);
        pnlMainHome.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void posterFilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posterFilm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posterFilm1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        pnlFilm2.setVisible(false);
        pnlMainHome.setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void posterFilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posterFilm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posterFilm2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPesanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane areaSinopsis;
    private javax.swing.JScrollPane areaSinopsis2;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBook1;
    private javax.swing.JButton btnBook2;
    private javax.swing.JButton btnFilm1;
    private javax.swing.JButton btnFilm2;
    private javax.swing.JButton btnFilm3;
    private javax.swing.JButton btnFilm4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDurasi;
    private javax.swing.JLabel lblDurasi2;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblHeading3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JLabel lblWhatsNow;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlBottom2;
    private javax.swing.JPanel pnlBottom3;
    private javax.swing.JPanel pnlFilm1;
    private javax.swing.JPanel pnlFilm2;
    public static javax.swing.JPanel pnlMainHome;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlTop2;
    private javax.swing.JPanel pnlTop3;
    private javax.swing.JButton posterFilm1;
    private javax.swing.JButton posterFilm2;
    private javax.swing.JTextArea txtSinopsis;
    private javax.swing.JTextArea txtSinopsis2;
    // End of variables declaration//GEN-END:variables
}
