package View;

/**
 *
 * @author anasyalaili
 */
import Model.Film;
import Model.Pengguna;
import javax.swing.ImageIcon;

public class ViewFilm extends javax.swing.JFrame {    
    private static Film selectedFilm;        
    private static Pengguna user;
    
    /**
     * Creates new form GUIFilm
     * //@param viewHome
     * @param selectedFilm
     * @param user
     */
    public ViewFilm(Film selectedFilm, Pengguna user) {
        initComponents();        
        this.selectedFilm = selectedFilm;
        this.user = user;
        setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon(selectedFilm.getPosterPath1());
        posterFilm.setIcon(icon);
        
        txtSinopsis.setEditable(false);
        lblJudul.setText(selectedFilm.getJudul());
        lblGenre.setText(selectedFilm.getGenre());
        lblDurasi.setText(selectedFilm.getDurasi());
        txtSinopsis.setText(selectedFilm.getSinopsis());        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFilm = new javax.swing.JPanel();
        pnlTop2 = new javax.swing.JPanel();
        lblHeading2 = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblDurasi = new javax.swing.JLabel();
        posterFilm = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        pnlBottom2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        areaSinopsis = new javax.swing.JScrollPane();
        txtSinopsis = new javax.swing.JTextArea();
        lblGenre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFilm.setBackground(new java.awt.Color(69, 69, 69));
        pnlFilm.setToolTipText("");
        pnlFilm.setPreferredSize(new java.awt.Dimension(900, 600));
        pnlFilm.setSize(new java.awt.Dimension(900, 600));

        pnlTop2.setBackground(new java.awt.Color(74, 99, 124));

        lblHeading2.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblHeading2.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading2.setText("CINEMAXX");

        javax.swing.GroupLayout pnlTop2Layout = new javax.swing.GroupLayout(pnlTop2);
        pnlTop2.setLayout(pnlTop2Layout);
        pnlTop2Layout.setHorizontalGroup(
            pnlTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTop2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTop2Layout.setVerticalGroup(
            pnlTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTop2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblHeading2)
                .addGap(30, 30, 30))
        );

        lblJudul.setFont(new java.awt.Font("Helvetica Neue", 1, 27)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("Avengers: Endgame");

        btnBack.setBackground(new java.awt.Color(60, 80, 100));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDurasi.setForeground(new java.awt.Color(255, 255, 255));
        lblDurasi.setText("3h 1m");

        posterFilm.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/1poster_endgame.jpg")); // NOI18N
        posterFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posterFilmActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(60, 80, 100));
        btnBook.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setText("Book Now >>");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        pnlBottom2.setBackground(new java.awt.Color(74, 99, 124));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ABOUT CINEMAXX");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FAQ");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONTACT US");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MEMBERSHIP");

        javax.swing.GroupLayout pnlBottom2Layout = new javax.swing.GroupLayout(pnlBottom2);
        pnlBottom2.setLayout(pnlBottom2Layout);
        pnlBottom2Layout.setHorizontalGroup(
            pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottom2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33))
        );
        pnlBottom2Layout.setVerticalGroup(
            pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottom2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtSinopsis.setBackground(new java.awt.Color(69, 69, 69));
        txtSinopsis.setColumns(20);
        txtSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        txtSinopsis.setLineWrap(true);
        txtSinopsis.setRows(5);
        txtSinopsis.setText("After Thanos' tragic defeat that wiped out half the universe, the remaining Avengers unite to travel back in time, collect the Infinity Stones, and reverse the destruction. In an epic final battle, they face Thanos once again to save the world—sacrificing many, including Iron Man, who dies in the name of humanity's victory.");
        areaSinopsis.setViewportView(txtSinopsis);

        lblGenre.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblGenre.setForeground(new java.awt.Color(255, 255, 255));
        lblGenre.setText("Action/Sci-Fi");

        javax.swing.GroupLayout pnlFilmLayout = new javax.swing.GroupLayout(pnlFilm);
        pnlFilm.setLayout(pnlFilmLayout);
        pnlFilmLayout.setHorizontalGroup(
            pnlFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFilmLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(posterFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudul)
                    .addGroup(pnlFilmLayout.createSequentialGroup()
                        .addComponent(lblGenre)
                        .addGap(18, 18, 18)
                        .addComponent(lblDurasi)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlFilmLayout.setVerticalGroup(
            pnlFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFilmLayout.createSequentialGroup()
                .addComponent(pnlTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(pnlFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posterFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFilmLayout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDurasi)
                            .addComponent(lblGenre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(areaSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(pnlBottom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFilm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        ViewHome viewHome = new ViewHome(user); 
        viewHome.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void posterFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posterFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posterFilmActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        if (user == null){
            ViewRegister viewRegister = new ViewRegister(selectedFilm);
            viewRegister.setVisible(true);        
        } else {
            PilihStudio pilihStudio = new PilihStudio(selectedFilm, user);
            pilihStudio.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFilm(selectedFilm, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane areaSinopsis;
    private javax.swing.JButton btnBack;
    public javax.swing.JButton btnBook;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblDurasi;
    public javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblHeading2;
    public javax.swing.JLabel lblJudul;
    private javax.swing.JPanel pnlBottom2;
    public javax.swing.JPanel pnlFilm;
    private javax.swing.JPanel pnlTop2;
    public javax.swing.JButton posterFilm;
    public javax.swing.JTextArea txtSinopsis;
    // End of variables declaration//GEN-END:variables
}
