package View;

import Model.Film;
import Model.Pengguna;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author anasyalaili
 */
public class ViewHome extends javax.swing.JFrame {
    private ViewFilm viewFilm;
    private ViewHome viewHome;
    private static Pengguna user;
    private ArrayList<Film> dataFilm = new ArrayList<>();
    private ArrayList<JButton> filmButtons;
    private Film selectedFilm;
    int i = 0;
    private boolean isMoreThan4;
    
    /**
     * Creates new form TestingHome
     * @param user
     */
    public ViewHome(Pengguna user) {
        initComponents();
        setLocationRelativeTo(null); 
        readFilmData();
        initializeFilmButtons();
        updateFilmPosters();
        this.user = user;
    }
    
    private void readFilmData() {
        try {
            try (BufferedReader reader = new BufferedReader(new FileReader("dataFilm.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split("\\|");                                        
                    if (parts.length == 7) {
                        dataFilm.add(new Film(parts[0], parts[1], parts[2], parts[3], parts[4], parts[5], parts[6]));                        
                        i++;                        
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Failed to load film data.");
        }
    }
    
    private void initializeFilmButtons() {        
        filmButtons = new ArrayList<>(Arrays.asList(btnFilm1, btnFilm2, btnFilm3, btnFilm4,btnFilm5, btnFilm6, btnFilm7, btnFilm8));
    }
        
    public void updateFilmPosters() {        
        if (dataFilm == null || dataFilm.isEmpty()) {                       
            for (JButton button : filmButtons) {
                button.setIcon(null); 
                button.setEnabled(false);                 
            }
            return;
        }

        for (int i = 0; i < filmButtons.size(); i++) {
            JButton currentButton = filmButtons.get(i);
            
            if (i < dataFilm.size()) {                
                Film selectedFilm = dataFilm.get(i);                                
                try {                    
                    if (selectedFilm.getPosterPath2() != null && !selectedFilm.getPosterPath2().isEmpty()) {
                        ImageIcon icon = new ImageIcon(selectedFilm.getPosterPath2());
                        currentButton.setIcon(icon); 
                        currentButton.setEnabled(true);                         
                        currentButton.setText(""); 
                    } else {                        
                        System.err.println("Poster path kosong untuk film: " + selectedFilm.getJudul());
                        currentButton.setIcon(null);
                        currentButton.setText(selectedFilm.getJudul() + "\n(Poster Tidak Tersedia)"); 
                        currentButton.setEnabled(false);                         
                    }
                } catch (Exception e) {                    
                    System.err.println("Gagal memuat poster untuk film " + selectedFilm.getJudul() + ": " + e.getMessage());
                    currentButton.setIcon(null);
                    currentButton.setText(selectedFilm.getJudul() + "\n(Error Memuat Poster)");
                    currentButton.setEnabled(false);                     
                }
            } else {
                currentButton.setIcon(null); 
                currentButton.setText(""); 
                currentButton.setEnabled(false); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollFilm = new javax.swing.JScrollPane();
        pnlMainHome = new javax.swing.JPanel();
        btnFilm1 = new javax.swing.JButton();
        btnFilm2 = new javax.swing.JButton();
        btnFilm3 = new javax.swing.JButton();
        btnFilm4 = new javax.swing.JButton();
        btnFilm5 = new javax.swing.JButton();
        btnFilm6 = new javax.swing.JButton();
        btnFilm7 = new javax.swing.JButton();
        btnFilm8 = new javax.swing.JButton();
        lblWhatsNow = new javax.swing.JLabel();
        pnlTop = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnForAdmin = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollFilm.setBorder(null);
        scrollFilm.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollFilm.setPreferredSize(new java.awt.Dimension(900, 425));
        scrollFilm.setSize(new java.awt.Dimension(900, 425));

        pnlMainHome.setBackground(new java.awt.Color(69, 69, 69));
        pnlMainHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMainHome.setPreferredSize(new java.awt.Dimension(1735, 600));
        pnlMainHome.setSize(new java.awt.Dimension(1735, 600));

        btnFilm1.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_endgame.jpg")); // NOI18N
        btnFilm1.setIconTextGap(0);
        btnFilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm1ActionPerformed(evt);
            }
        });

        btnFilm2.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_TTB.jpg")); // NOI18N
        btnFilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm2ActionPerformed(evt);
            }
        });

        btnFilm3.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_interstellar.jpg")); // NOI18N
        btnFilm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm3ActionPerformed(evt);
            }
        });

        btnFilm4.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/NetBeansProjects/TicketingBioskop/homeposter_28yearslater.jpg")); // NOI18N
        btnFilm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm4ActionPerformed(evt);
            }
        });

        btnFilm5.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_endgame.jpg")); // NOI18N
        btnFilm5.setIconTextGap(0);
        btnFilm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm5ActionPerformed(evt);
            }
        });

        btnFilm6.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_TTB.jpg")); // NOI18N
        btnFilm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm6ActionPerformed(evt);
            }
        });

        btnFilm7.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_interstellar.jpg")); // NOI18N
        btnFilm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm7ActionPerformed(evt);
            }
        });

        btnFilm8.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/NetBeansProjects/TicketingBioskop/homeposter_28yearslater.jpg")); // NOI18N
        btnFilm8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm8ActionPerformed(evt);
            }
        });

        lblWhatsNow.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblWhatsNow.setForeground(new java.awt.Color(255, 255, 255));
        lblWhatsNow.setText("Now Showing");

        javax.swing.GroupLayout pnlMainHomeLayout = new javax.swing.GroupLayout(pnlMainHome);
        pnlMainHome.setLayout(pnlMainHomeLayout);
        pnlMainHomeLayout.setHorizontalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWhatsNow)
                    .addGroup(pnlMainHomeLayout.createSequentialGroup()
                        .addComponent(btnFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlMainHomeLayout.setVerticalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblWhatsNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFilm8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilm7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFilm6, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilm5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 250, Short.MAX_VALUE))
        );

        scrollFilm.setViewportView(pnlMainHome);

        scrollFilm.setViewportView(pnlMainHome);

        pnlTop.setBackground(new java.awt.Color(74, 99, 124));

        lblHeading.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setText("CINEMAXX");

        btnForAdmin.setBackground(new java.awt.Color(74, 99, 124));
        btnForAdmin.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/NetBeansProjects/TicketingBioskop/settingscopy2.png")); // NOI18N
        btnForAdmin.setBorder(null);
        btnForAdmin.setBorderPainted(false);
        btnForAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnForAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnForAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pnlBottom.setBackground(new java.awt.Color(74, 99, 124));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOUT CINEMAXX");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FAQ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTACT US");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MEMBERSHIP");

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm1ActionPerformed
        this.dispose();
        viewFilm = new ViewFilm(dataFilm.get(0), user);                
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm1ActionPerformed

    private void btnFilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm2ActionPerformed
        this.dispose();
        viewFilm = new ViewFilm(dataFilm.get(1), user);                       
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm2ActionPerformed

    private void btnFilm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm3ActionPerformed
        this.dispose();
        viewFilm = new ViewFilm(dataFilm.get(2), user);                       
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm3ActionPerformed

    private void btnFilm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm4ActionPerformed
        this.dispose();
        viewFilm = new ViewFilm(dataFilm.get(3), user);                      
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm4ActionPerformed

    private void btnFilm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm5ActionPerformed
        if (dataFilm.size() == 5){
            this.dispose();
            viewFilm = new ViewFilm(dataFilm.get(4), user);                            
            viewFilm.setVisible(true);
        }
    }//GEN-LAST:event_btnFilm5ActionPerformed

    private void btnFilm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm6ActionPerformed
        if (dataFilm.size() == 6){
            this.dispose();
            viewFilm = new ViewFilm(dataFilm.get(5), user);                            
            viewFilm.setVisible(true);
        }
    }//GEN-LAST:event_btnFilm6ActionPerformed

    private void btnFilm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm7ActionPerformed
        if (dataFilm.size() == 7){
            this.dispose();
            viewFilm = new ViewFilm(dataFilm.get(6), user);                            
            viewFilm.setVisible(true);
        }
    }//GEN-LAST:event_btnFilm7ActionPerformed

    private void btnFilm8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm8ActionPerformed
        if (dataFilm.size() == 8){
            this.dispose();
            viewFilm = new ViewFilm(dataFilm.get(7), user);                            
            viewFilm.setVisible(true);
        }
    }//GEN-LAST:event_btnFilm8ActionPerformed

    private void btnForAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForAdminActionPerformed
        try {
            String inputKode = JOptionPane.showInputDialog(this, "Input Code:", "Admin Access", JOptionPane.PLAIN_MESSAGE);
            if (inputKode.equals("a")) {        
                JOptionPane.showMessageDialog(this, "Access granted!", "Success", JOptionPane.INFORMATION_MESSAGE);                
                RegisterAdmin registerAdmin = new RegisterAdmin();
                registerAdmin.setVisible(true);
                this.dispose();
            } else if (inputKode.isEmpty()) {
                JOptionPane.showMessageDialog(this,"Please fill the field.", "Code is blank", JOptionPane.ERROR_MESSAGE);              
            } else {
                JOptionPane.showMessageDialog(this,"Code is wrong. Access denied.", "Unsuccessful", JOptionPane.ERROR_MESSAGE);            
            }  
        } catch (NullPointerException e) {
            System.out.println("The input is null.");
        }
    }//GEN-LAST:event_btnForAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilm1;
    private javax.swing.JButton btnFilm2;
    private javax.swing.JButton btnFilm3;
    private javax.swing.JButton btnFilm4;
    private javax.swing.JButton btnFilm5;
    private javax.swing.JButton btnFilm6;
    private javax.swing.JButton btnFilm7;
    private javax.swing.JButton btnFilm8;
    private javax.swing.JButton btnForAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblWhatsNow;
    private javax.swing.JPanel pnlBottom;
    public javax.swing.JPanel pnlMainHome;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrollFilm;
    // End of variables declaration//GEN-END:variables
}
